Added UserLocalStorageService
Stasiek99/AA-Angular-public pull request #18
Opened 2022-07-22 15:46 UTC by Stasiek99

2022-07-25 20:41 UTC, kamazowe commented
if I go to the site and the user has not been added yet, I get an error in the console

2022-07-25 20:52 UTC, kamazowe requested changes

2022-07-25 20:52 UTC, kamazowe commented on src/app/create-new-user/components/create-new-user/create-new-user.component.ts
> +  //
comment ??

2022-07-25 20:52 UTC, kamazowe commented on src/app/user/user-local-storage.service.ts
> +  createdUser: UserInterface | null = null;
this service should not contain application state

2022-07-25 20:52 UTC, kamazowe commented on src/app/user/user-local-storage.service.ts
> +    let localStorageFields = window.localStorage["User"];
return JSON.parse(localStorageFields);

2022-07-25 20:52 UTC, kamazowe commented on src/app/user/user-local-storage.service.ts
> +export class UserLocalStorageService {
UserService should communicate with this service

2022-07-25 20:52 UTC, kamazowe commented on src/app/user-presentation/components/user-presentation.component.ts
> +    window.location.reload();
if you can, then don't use the global object. try to do it another way

2022-07-25 20:52 UTC, kamazowe commented on src/app/user-presentation/components/user-presentation.component.ts
> +    window.localStorage.removeItem("User");
why does the user presentation component know about localstorage? only UserLocalStorageService can know about localstorage.only in the above class you can use `window.localStorage`

2022-07-25 20:52 UTC, kamazowe commented on src/app/user-presentation/components/user-presentation.component.html
> +      <button mat-raised-button *ngIf="this.isButtonVisible" (click)="deleteUser()">Delete User</button>
this.isButtonVisible > isButtonVisible

2022-07-25 20:52 UTC, kamazowe commented on src/app/user-presentation/components/user-presentation.component.ts
>      console.log(this.user)
cls?

2022-07-25 20:52 UTC, kamazowe commented on src/app/shared/shared-form/user-form.component.ts
> +  ngOnInit(): void {
lint error

2022-07-28 16:18 UTC, kamazowe requested changes

2022-07-28 16:18 UTC, kamazowe commented on src/app/user/user-state.service.ts
> +export class UserStateService {
good job, this service looks cool

2022-07-28 16:18 UTC, kamazowe commented on src/app/user/user-state.service.ts
> +  constructor(private userLocalStorageService: UserLocalStorageService) {}
I propose to initially assign the value from localstorage to the createdUser field in constructor
.then you can simplify the `getUser` method

2022-07-28 16:18 UTC, kamazowe commented on src/app/user/user-state.service.ts
> +  deleteUser(){
Should we only delete data from localstorage?

2022-07-29 10:55 UTC, Stasiek99 commented on src/app/create-new-user/components/create-new-user/create-new-user.component.ts
>     let dialogRef = this.dialog.open(DialogCreateUserComponent, {
When I remove 22nd line of code, 30th line does not execute

2022-07-29 10:57 UTC, Stasiek99 commented on src/app/create-new-user/components/create-new-user/create-new-user.component.ts
>     let dialogRef = this.dialog.open(DialogCreateUserComponent, {
When I delete 22nd line of code, 30th does not execute

2022-07-31 14:31 UTC, kamazowe approved these changes

2022-07-31 15:33 UTC, merged